# Generated by Django 5.1.3 on 2024-11-14 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('orders', 'Отчет по заказам'), ('dishes', 'Отчет по блюдам'), ('delivery', 'Отчет по доставке')], max_length=20, verbose_name='Тип отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_path', models.FileField(upload_to='reports/', verbose_name='Файл отчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
