# Generated by Django 5.1.3 on 2024-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя и фамилия')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Включить email-уведомления')),
                ('whatsapp_notifications', models.BooleanField(default=True, verbose_name='Включить WhatsApp-уведомления')),
                ('email_recipient', models.EmailField(max_length=254, verbose_name='Email для уведомлений')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер WhatsApp')),
            ],
        ),
    ]
